#include "common_types_2d.h"

namespace fem {

FEM_DEFINE_STRUCT(Tri);
FEM_BEGIN_PROPERTY_REGISTER(Tri)
{
    FEM_REGISTER_PROPERTY(Tri, v);
    FEM_REGISTER_PROPERTY(Tri, id);
    FEM_REGISTER_PROPERTY(Tri, neighbors);
    FEM_REGISTER_PROPERTY(Tri, valid);
}
FEM_END_PROPERTY_REGISTER(Tri);

FEM_DEFINE_STRUCT(Edge);
FEM_BEGIN_PROPERTY_REGISTER(Edge)
{
    FEM_REGISTER_PROPERTY(Edge, a);
    FEM_REGISTER_PROPERTY(Edge, b);
    FEM_REGISTER_PROPERTY(Edge, on_boundary);
}
FEM_END_PROPERTY_REGISTER(Edge);

FEM_DEFINE_STRUCT(EdgeInfo)
FEM_BEGIN_PROPERTY_REGISTER(EdgeInfo)
{
    FEM_REGISTER_PROPERTY(EdgeInfo, a);
    FEM_REGISTER_PROPERTY(EdgeInfo, b);
    FEM_REGISTER_PROPERTY(EdgeInfo, tri_left);
    FEM_REGISTER_PROPERTY(EdgeInfo, tri_right);
    FEM_REGISTER_PROPERTY(EdgeInfo, on_boundary);
    FEM_REGISTER_PROPERTY(EdgeInfo, boundary_tag);
}
FEM_END_PROPERTY_REGISTER(EdgeInfo);

FEM_DEFINE_STRUCT(Point2D);
FEM_BEGIN_PROPERTY_REGISTER(Point2D)
{
    FEM_REGISTER_PROPERTY(Point2D, p);
    FEM_REGISTER_PROPERTY(Point2D, id);
    FEM_REGISTER_PROPERTY(Point2D, on_boundary);
    FEM_REGISTER_PROPERTY(Point2D, incident_triangles);
}
FEM_END_PROPERTY_REGISTER(Point2D);

}