include_guard(GLOBAL)

include(FetchContent)

set(FETCHCONTENT_QUIET OFF)
set(FETCHCONTENT_UPDATES_DISCONNECTED ON)
set(ENV{GIT_TERMINAL_PROMPT} 0)

if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/LLGL/CMakeLists.txt")
  message(STATUS "Using local LLGL at: ${CMAKE_CURRENT_SOURCE_DIR}/LLGL")
  set(FETCHCONTENT_SOURCE_DIR_LLGL "${CMAKE_CURRENT_SOURCE_DIR}/LLGL")
endif()

set(LLGL_BUILD_RENDERER_DIRECT3D11 OFF CACHE BOOL "" FORCE)
set(LLGL_BUILD_RENDERER_VULKAN OFF CACHE BOOL "" FORCE)

if(APPLE)
  set(LLGL_BUILD_RENDERER_METAL ON CACHE BOOL "" FORCE)
elseif(WIN32)
  set(LLGL_BUILD_RENDERER_DIRECT3D12 ON CACHE BOOL "" FORCE)
  set(LLGL_D3D12_ENABLE_DXCOMPILER ON CACHE BOOL "" FORCE)
  set(LLGL_BUILD_RENDERER_METAL OFF CACHE BOOL "" FORCE)
endif()

set(LLGL_BUILD_RENDERER_OPENGL OFF CACHE BOOL "" FORCE)
set(LLGL_BUILD_RENDERER_OPENGLES OFF CACHE BOOL "" FORCE)
set(LLGL_BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(LLGL_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(LLGL_BUILD_STATIC_LIB ON CACHE BOOL "" FORCE)
set(LLGL_BUILD_DEBUG_LAYER ON CACHE BOOL "" FORCE)

FetchContent_Declare(
  LLGL
  GIT_REPOSITORY https://github.com/LukasBanana/LLGL.git
  GIT_TAG master
)
FetchContent_MakeAvailable(LLGL)

FetchContent_Declare(
  glfw
  GIT_REPOSITORY https://github.com/glfw/glfw.git
  GIT_TAG 3.4
)
FetchContent_MakeAvailable(glfw)

FetchContent_Declare(
  glm
  GIT_REPOSITORY https://github.com/g-truc/glm.git
  GIT_TAG 1.0.2
)
FetchContent_MakeAvailable(glm)

set(SLANG_ENABLE_CUDA OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_SLANG_RHI OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_TESTS OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_AFTERMATH OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_GFX OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_OPTIX OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_SLANGI OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_SLANGD OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_SLANG_GLSLANG OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_REPLAYER OFF CACHE BOOL "" FORCE)
set(SLANG_EXCLUDE_DAWN OFF CACHE BOOL "" FORCE)
set(SLANG_LIB_TYPE STATIC CACHE BOOL "" FORCE)

FetchContent_Declare(
  slang
  GIT_REPOSITORY https://github.com/shader-slang/slang
  GIT_TAGE v2026.10.2
)
FetchContent_MakeAvailable(slang)