if(NOT DEFINED LLGL_SOURCE_DIR)
  message(FATAL_ERROR "LLGL_SOURCE_DIR is required")
endif()

set(LLGL_METAL_SHADER "${LLGL_SOURCE_DIR}/sources/Renderer/Metal/Shader/MTShader.mm")
file(READ "${LLGL_METAL_SHADER}" LLGL_METAL_SHADER_SOURCE)

if(NOT LLGL_METAL_SHADER_SOURCE MATCHES "CHECK_MTL_LANGUAGE_VERSION\\(2, 4")
  string(REPLACE
    [=[        CHECK_MTL_LANGUAGE_VERSION(2, 2, macOS 10.15, iOS 13.0, *);]=]
    [=[        CHECK_MTL_LANGUAGE_VERSION(2, 4, macOS 12.0, iOS 15.0, *);
        CHECK_MTL_LANGUAGE_VERSION(2, 3, macOS 11.0, iOS 14.0, *);
        CHECK_MTL_LANGUAGE_VERSION(2, 2, macOS 10.15, iOS 13.0, *);]=]
    LLGL_METAL_SHADER_SOURCE
    "${LLGL_METAL_SHADER_SOURCE}"
  )

  if(NOT LLGL_METAL_SHADER_SOURCE MATCHES "CHECK_MTL_LANGUAGE_VERSION\\(2, 4")
    message(FATAL_ERROR "Failed to patch LLGL Metal language versions")
  endif()

  file(WRITE "${LLGL_METAL_SHADER}" "${LLGL_METAL_SHADER_SOURCE}")
endif()
